### ISSUE TITLE
Guidance on running this

### ISSUE THREAD

**Issue by amirkhan81** [digidem/mosaic-image-stream#2]
Could you provide any guidance on actually running this?

Downloaded example, ran npm install to grab dependencies, added "start": "node index.js" to the package.json, npm run, nothing...

Maybe missing something small?

**Comment by gmaclennan** [comment]
Hi @amirkhan81 the usage examples are listed in the [README.md](https://github.com/digidem/mosaic-image-stream#usage). These same scripts are in the [/example](https://github.com/digidem/mosaic-image-stream/tree/master/example) folder. You can run these scripts from the command line by typing:

```sh
node example/mosaic_files.js
```

You won't see anything happen, since I accidentally checked in the generated file ([example/file_mosaic.png](https://github.com/digidem/mosaic-image-stream/blob/master/example/file_mosaic.png)) but you will see that that file has been over-written after running the example.

The [Flickr example](https://github.com/digidem/mosaic-image-stream/blob/master/example/mosaic_flickr.js) does not currently complete because the Flickr API incorrectly returns images which are not 200px x 200px (despite this being requested) and the module currently does not have a way of mosaicing differently sized images.

The [Map example](https://github.com/digidem/mosaic-image-stream/blob/master/example/mosaic_map.js) will give you a lot of `Possible EventEmitter memory leak detected` warnings and it will take a while, but it should work fine, resulting in a 17,000px jpg map. Not sure about how to remove these warnings, I should probably just do what the warning says and use `emitter.setMaxListeners()`

**Comment by amirkhan81** [comment]
Yep! that works, just a heads up, looks like tilebelt is missing as a dependency.

**Comment by gmaclennan** [comment]
thanks fixed in 0cae99e
